name: Cosmos DB Emulator Test
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Cosmos DB Emulator
        run: |
          & 'C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe' start /NoUI
          Start-Sleep -Seconds 140
        shell: powershell

      - name: Check connection
        run: |
          curl https://localhost:8081/_explorer/index.html
        shell: powershell
