name: Cosmos DB Emulator Test
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Azure Cosmos DB Emulator
        run: |
          Set-Location "C:\Program Files\Azure Cosmos DB Emulator"
          .\Microsoft.Azure.Cosmos.Emulator.exe /Start /NoUI /NoExplorer
          # Wait for the emulator to fully start
          Start-Sleep -Seconds 240
          .\Microsoft.Azure.Cosmos.Emulator.exe /GetStatus
          # Check Connection
          curl https://localhost:8081/_explorer/index.html
        shell: pwsh
